
#include	"MyDefine.h"

volatile 		unsigned char  	gu8v_Delay1mS;
volatile 		unsigned char  	gu8v_Delay5mS;
volatile 		unsigned char  	gu8v_Delay10mS;
volatile 		unsigned char  	gu8v_Delay100mS;
volatile 		unsigned char  	gu8v_Delay50mS;
volatile 		unsigned char  	gu8v_Delay500mS;
volatile 		unsigned char  	gu8v_Delay1S;

volatile		unsigned char  	gu8v_BeepStep;
volatile		unsigned char  	gu8v_BeepTime;
volatile		unsigned char  	gu8v_TimerMode;
volatile		unsigned char  	gu8v_BeepType;
volatile		unsigned char  	gu8v_BeepCnt;

volatile		unsigned char  	gu8v_WorkMode;
volatile		unsigned char  	gu8v_AbPwmDuty;
volatile		unsigned char  	gu8v_AbPwmDelay;
volatile		unsigned char  	gu8v_FunPwmDuty;
volatile		unsigned char  	gu8v_FunPwmDelay;

volatile		unsigned char  	gu8v_AbPwmOutPinDuty;
volatile		unsigned char  	gu8v_AbPwmOutPinDelay;
volatile		unsigned char  	gu8v_FunPwmOutPinDuty;
volatile		unsigned char  	gu8v_FunPwmOutPinDelay;

volatile		unsigned char  	gu8v_PressureMode;
//volatile		unsigned char  	gu8v_PressureModeCopy=0;
volatile		unsigned char  	gu8v_JiaoTiMode;

volatile		unsigned char 	gu8v_KeyDebounce;
volatile		unsigned char 	gu8v_KeyOffDebounce;
volatile		unsigned char  	gu8v_KeyLongDelay;
volatile		unsigned int  	gu16v_KeyBuffer;
volatile		unsigned int  	gu16v_KeyValue;
volatile		unsigned int  	gu16v_JiaoTiTime;
volatile		unsigned int  	gu16v_JiaoTiTimeCnt;
volatile		unsigned int  	gu16v_JiaoTiTimeCmp;
volatile 		unsigned char	gu8v_DisplayBuf[14];
volatile		unsigned char  	gu8v_IrRecData[4];
volatile		unsigned char  	gu8v_IrDelay;
volatile		unsigned char  	gu8v_IrBitCnt;
volatile		unsigned char  	gu8v_IrSampling;
volatile		unsigned char  	gu8v_IrSampStep;
volatile		unsigned int  	gu16v_AutoModeCycle;
volatile		unsigned char  	gu8v_12vInDebounce;
volatile		unsigned char  	gu8v_12vOutDebounce;
volatile		unsigned char  	gu8v_AcOffDebounce;
volatile  		unsigned char 	gu8v_AdSampCnt1;
volatile  		unsigned int 	gu16v_AdMaxTemp1;
volatile  		unsigned int 	gu16v_AdMinTemp1;
volatile  		unsigned int 	gu16v_AdcValue1;
volatile  		unsigned char 	gu8v_AdSampCnt2;
volatile  		unsigned int 	gu16v_AdMaxTemp2;
volatile  		unsigned int 	gu16v_AdMinTemp2;
volatile  		unsigned int 	gu16v_AdcValue2;
volatile  		unsigned int 	gu16v_ABAdcSensor;
volatile  		unsigned int 	gu16v_FunAdcSensor;
volatile		unsigned int 	gu16v_CalData;
volatile		unsigned int	gu16v_Ab7P5mmHgData;
volatile		unsigned int	gu16v_Ab150CalDataEe;
volatile		unsigned int	gu16v_Ab150CalDataEeCopy;
volatile		unsigned int	gu16v_AbAdcZeroData;
volatile		unsigned int	gu16v_AbAdcZeroDataSum;
volatile		unsigned int	gu16v_AbSensroCalCopy;
volatile		unsigned int	gu16v_AbSensroCmp;
volatile		unsigned int	gu16v_EeTemp;
volatile		unsigned char	gu8v_AbPressureNoFullCmp;
volatile		unsigned char	gu8v_AbPressureNoFullAdcCnt;
volatile		unsigned char	gu8v_AbPressureFullAdcCnt;
volatile		unsigned char	gu8v_AbPressureLowNorAdcCnt;

volatile		unsigned int	gu16v_Fun7P5mmHgData;
volatile		unsigned int	gu16v_Fun150CalDataEe;
volatile		unsigned int	gu16v_Fun150CalDataEeCopy;
volatile		unsigned int	gu16v_FunAdcZeroData;
volatile		unsigned int	gu16v_FunAdcZeroDataSum;
volatile		unsigned int	gu16v_FunSensroCalCopy;
volatile		unsigned int	gu16v_FunSensroCmp;
volatile		unsigned char	gu8v_FunPressureNoFullCmp;
volatile		unsigned char	gu8v_FunPressureLowAdcCnt;
volatile		unsigned char	gu8v_FunPressureFullAdcCnt;
volatile		unsigned char	gu8v_FactoryDebounce;
volatile		unsigned char	gu8v_CalDcfScan;

volatile		unsigned char	gu8v_CalModeIndex;
volatile		unsigned char	gu8v_AbGetAdcZeroCnt;
volatile		unsigned char  	gu8v_BatLowCnt;
volatile		unsigned char  	gu8v_BatNormalCnt;
volatile		unsigned char	gu8v_UartDelayClearRxIndex;
volatile		unsigned char	gu8v_UartRxLength;
volatile		unsigned char	gu8v_UartTxIndex;
volatile		unsigned char	gu8v_UartTxLength;
volatile		unsigned char	gu8v_ButtonOnTkDelay;
volatile		unsigned char	gu8v_PowerOnDelay;
volatile		unsigned char	gu8v_LvdDebounce;
volatile		unsigned char	gu8v_RfIdCopyTime;
volatile		unsigned char	gu8v_RfIdCopyKeyCnt;
volatile		unsigned char	gu8v_RfIdCopyLedDisStep;
volatile		unsigned char	gu8v_433RecData[6];
volatile		unsigned char	gu8v_433RecValue[6];
volatile		unsigned char	gu8v_433CopyIdData1[4];
volatile		unsigned char	gu8v_433_H_cnt;
volatile		unsigned char 	gu8v_433_L_Cnt;
volatile		unsigned char 	gu8v_433BitCnt;
volatile		unsigned char 	gu8v_433ByteCnt;
volatile		unsigned char 	gu8v_VoicePluse;
volatile		unsigned char 	gu8v_KeyBuf1;
volatile		unsigned char 	gu8v_KeyBuf2;
volatile		unsigned char 	gu8v_KeyBuf3;
volatile		unsigned char 	gu8v_LockDelay60S;
volatile		unsigned char 	gu8v_PreKeyDownDisTime;
//volatile		unsigned char 	gu8v_IdLowByte=0;
//volatile		unsigned char 	gu8v_IdHighByte=0;
volatile		unsigned char	gu8v_UartTxBuf[20];
volatile		unsigned char	gu8v_UartRxBuf[20];
volatile 		unsigned 	char 	gu8v_RfSendStep;
volatile 		unsigned 	char 	gu8v_RfSendCycle;
volatile 		unsigned 	char 	gu8v_RfBitCycle;
volatile 		unsigned 	char 	gu8v_RfBitDuty;
volatile 		unsigned 	char 	gu8v_RfSendByteCnt;
volatile 		unsigned 	char 	gu8v_RfSendBitCnt;
volatile 		unsigned 	char 	gu8v_AbNumDisValue;
volatile 		unsigned 	char 	gu8v_AbNumDisCurrentValue;
volatile 		unsigned 	int 	gu16v_AbNumDisValueOld;
volatile 		unsigned 	char 	gu8v_FunNumDisValue;
volatile 		unsigned 	char 	gu8v_NumDisTemp;
volatile 		unsigned 	char 	gu8v_PressureModeCopy;
volatile		unsigned 	int		gu16v_AbPressureLowErrTimeCmp;
volatile		unsigned 	int		gu16v_AbPressureLowErrTimeCnt;
volatile		unsigned 	int		gu16v_FunPressureLowErrTimeCmp;
volatile		unsigned 	int		gu16v_FunPressureLowErrTimeCnt;

volatile 		unsigned 	char 	gu8v_AbSensorPressureCnt;
volatile 		unsigned 	char 	gu8v_FunSensorPressureCnt;

volatile 		unsigned 	char 	gu8v_AbFangQiTime;
volatile 		unsigned 	char 	gu8v_AbSensorDisCnt;

volatile 		unsigned 	char 	gu8v_AbSensorLowPwmCnt;
volatile 		unsigned 	char 	gu8v_AbSensorHighPwmCnt;
volatile 		unsigned 	char 	gu8v_FunSensorLowPwmCnt;
volatile 		unsigned 	char 	gu8v_FunSensorHighPwmCnt;
volatile 		unsigned 	char 	gu8v_12KpDebounce;
volatile 		unsigned 	char 	gu8v_7KpDebounce;

volatile 		__flag_type			KeyFlag1;
volatile 		__flag_type			KeyFlag2;
volatile 		__flag_type			KeyFlag3;
volatile 		__flag_type			TimeFlag1;
volatile 		__flag_type			TimeFlag2;
volatile 		__flag_type			WorkFlag1;
volatile 		__flag_type			WorkFlag2;
volatile 		__flag_type			WorkFlag3;
volatile		__flag_type			WorkFlag4;
volatile		__flag_type			WorkFlag5;
volatile		__flag_type			WorkFlag6;
volatile		__flag_type			WorkModeFlag;
volatile 		__flag_type			DcfFlag1;

volatile 		__u16byte_type		gu16v_IdData;
